version: "3.9"

services:
  database:
    #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database_denounce_otavio
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=vinimachad
      - POSTGRES_PASSWORD=4224
      - POSTGRES_DB=denounce_otavio
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: denounce_otavio
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
